project:
  type: website
  render:
    - index.qmd
    - goals.qmd

website:
  title: "Quarto Qrew"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - goals.qmd
      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: source

